# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Your awesome title
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/growth-guide" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username: jekyll

permalink: /:path

# Build settings
remote_theme: just-the-docs/just-the-docs@v0.4.0.rc1
plugins:
  - jekyll-feed
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Just-the-docs specific configuration parameters
#
# Set a path/url to a logo that will be displayed instead of the title
logo: "/assets/images/logo-memo-bank-black.svg"
#
# Color scheme
# Color scheme currently only supports "dark", "light"/nil (default), or a custom
# scheme that you define
color_scheme: memo
#
# Aux links
# Aux links are located in the upper right navigation
aux_links:
  "vers memo.bank →":
    - "https://memo.bank"
# Makes aux links open in a new tab. Default is false.
aux_links_new_tab: true
#
# Heading anchor links
# Links that appear on hover over h1-h6 tags in page content allowing users to
# deep link to a particular heading on a page. Supports true (default) or false.
heading_anchors: true
#
# External navigation links
nav_external_links:
  - title: memo.bank
    url: https://memo.bank
    hide_icon: false # set to true to hide the external link icon - defaults to false
